### ISSUE TITLE
Node published as flow on flows.nodered.org and not available as node in app

### ISSUE THREAD

**Issue by bohtho** [caputomarcos/node-red-contrib-oauth2#1]
I am eager to try out this node but the node seems to only be published as flow (instead of node) on flows.nodered.org and not available as node in app.

**Comment by caputomarcos** [comment]
Hi @bohtho,
Thank you for reporting the problem. So, the last 3 commits fixes this problem, Please, could you check again? I hope you enjoy -  kind regards.
[see](https://flows.nodered.org/node/node-red-contrib-oauth2)
