### ISSUE TITLE
Problem with StatusCode if condition

### ISSUE THREAD

**Issue by codecracker2020** [caputomarcos/node-red-contrib-oauth2#19]
Hi Team,

I see the condition in the oauth.js for validating the status. When correct credentials are passed to oauth/token call, the statusCode will be 200, but the condition is as below:

**if (response && response.statusCode < 299 && response.statusCode > 200)  {**
 
So it will fail everytime.

**Comment by caputomarcos** [comment]
Hi fellow @codecracker2020 all done! Could you review it please? 

best regard

**Comment by codecracker2020** [comment]
Cool!.. Worked like a GEM
