### ISSUE TITLE
Maybe there is a bug with scope on Client credentials grant type?

### ISSUE THREAD

**Issue by HurukHai** [caputomarcos/node-red-contrib-oauth2#2]
Hi, I'm trying to connect to fitbit oauth2. I success can obtain a token for the api, but scope param on oauth2Response object is allways empty

```
{ 
   "authorization":"XXsuccessXX",
   "oauth2Response":{ 
      "statusCode":200,
      "statusMessage":"OK",
      "body":{ 
         "access_token":"XXXsuccessXXX",
         "expires_in":28800,
         "scope":"",
         "token_type":"Bearer"
      }
   }
}
```

As you can see I'm setting the scope:
![Captura de pantalla 2019-10-25 a las 1 57 10](https://user-images.githubusercontent.com/2548212/67533578-d5a99c00-f6ca-11e9-84c9-07ea6794cdb3.png)

**Comment by codecracker2020** [comment]
Yes I faced the same issue, when grant_type is set to password, I see from the code that they are deleting user credentials from the Body which is causing the issue. 
![image](https://user-images.githubusercontent.com/3763703/109156441-dbb7fd00-7796-11eb-862d-1f02663b8a3f.png)

Resulting in an error stating, Username is not provided.

**Comment by objt-ev** [comment]
Same issue with keycloak, when grant_type is set to password username and password MUST be present...

Now I am always getting error 401 unauthorized, error: "invalid_request"
error_description: "Missing parameter: username"

this makes version 3 of OAuth2 useless for me
