### ISSUE TITLE
Token Type Capitalisation

### ISSUE THREAD

**Issue by timhodson** [caputomarcos/node-red-contrib-oauth2#21]
When combined into an `Authorization` header value the `token_type` should be title case. 
The specific issue I was having was that the authentication protocol identifier `bearer` should be `Bearer` for oAuth servers which strictly implement the oAuth Spec [RFC6750](https://datatracker.ietf.org/doc/html/rfc6750#page-14).

The `token_type` in the response from the oAuth server is allowed to be lower case according to examples in [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749), but should be title case when used in this line...
https://github.com/caputomarcos/node-red-contrib-oauth2/blob/d98f152452cce47e52140ed7c69ed4005f008bdf/oauth2.js#L152

At the moment I am having to pre process the token output before using it in an HTTP request.

**Comment by caputomarcos** [comment]
Hi @timhodson, all done. Could you review it please? 

best regards,
