### ISSUE TITLE
oauth2 node not working

### ISSUE THREAD

**Issue by hawkseye76** [caputomarcos/node-red-contrib-oauth2#22]
getting this error message when i updated to latest version of oauth2

SyntaxError: Delete of an unqualified identifier in strict mode. (line:130)

**Comment by BertilJ** [comment]
Same issue for me, just noticed.

**Comment by timhodson** [comment]
The `delete options;` in line 130 doesn't seem to be needed as the options object is only declared in the previous 'on input' callback that starts on line 53. I think this line can just be removed.

**Comment by caputomarcos** [comment]
hi guys, thanks for the feedback. fixed
kind regards @pshellguruwannabe @BertilJ @timhodson

**Comment by hawkseye76** [comment]
everything looks good now.

Thanks
