### ISSUE TITLE
getting error "missing parameter" using grant type "refresh token"

### ISSUE THREAD

**Issue by WillyWurst** [caputomarcos/node-red-contrib-oauth2#23]
I am getting the error "HTTP400, {"error":"invalide_request","error_description":"Missing parameter:'refresh_token'","error_code":"invalide.request"} if I am using the "- Set by msg.oauth2Request -" Option sending the parameters via payload to the oauth2-node. Yesterday I updated from one of the previous versions and it was running smooth until the update. The setup of the msg.oauth2Request-parameters are done like in your documentation. The connected API seems to work as expected (logging in and using refresh token manually is working). Is this a bug or any tips / hints?
Thank you.

**Comment by caputomarcos** [comment]
Hi @WillyWurst, all done. could you please review it?

kind regards!

**Comment by WillyWurst** [comment]
Super duper!
I updated to version 2.0.4 and restarted node-red. After that the refresh-token option is working.
Great work!
Thank you very much!
