### ISSUE TITLE
RejectUnauthorized issue

### ISSUE THREAD

**Issue by EmanuelMiron** [caputomarcos/node-red-contrib-oauth2#25]
Hi, 

This is more of a question, 
I would like to use the changes made in the last commit in new node-red projects. 
How do you manage versioning, or when will you create a new version and publish the change to npm.

Thanks!

**Comment by caputomarcos** [comment]
@EmanuelMiron Oops, of course. can you test please? 3.0.2

kind regards!

**Comment by EmanuelMiron** [comment]
Thanks for the quick response,
It works like a charm :) 

When you have time, please update it in the node-red library aswell, but at least now I can install it manually and it works.

Thanks again!

**Comment by caputomarcos** [comment]
\o/ Done!

![image](https://user-images.githubusercontent.com/3945941/143149569-823c3b3a-e485-4384-b031-9453d7064c19.png)

kind regard!
