### ISSUE TITLE
"Error: invalid_grant" after a while

### ISSUE THREAD

**Issue by johnny-de** [caputomarcos/node-red-contrib-oauth2#26]
I have the problem that I keep getting the error message "Error: invalid_grant" after a while. When I set up the node, everything works fine and my values appear correctly in Google Fit. When I look the next day no more values ​​come in and the node shows "Error: invalid_grant". Then I have to set it up again and it will work again for a while. 

Does anyone have an idea why this is and how to solve it? Thx.

**Comment by caputomarcos** [comment]
Hi @johnny-de ,

Thank you for reaching out. Have you tried testing the application on version 4.1.5 to see if the issue still persists? Also, could you provide more information on how you are authenticating with Google Fit and what actions you are performing when the error occurs? This information will be helpful in troubleshooting the issue.

kind regards.
