### ISSUE TITLE
Log level on node-red console

### ISSUE THREAD

**Issue by sbollain-mlt** [caputomarcos/node-red-contrib-oauth2#29]
I have my settings.js configured with logging console level: "info"
However, every time the oauth2 node runs, my nodered console gets filled with many lines coming from the oath2 node that seems more debug info than any other thing. As an example:
<ref *2> IncomingMessage {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: true,
    ended: true,
    endEmitted: true,
    reading: false,
    constructed: true,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,

and many more lines

**Comment by serotonie** [comment]
see #31
