### ISSUE TITLE
redirect_uri

### ISSUE THREAD

**Issue by Dunnenj** [caputomarcos/node-red-contrib-oauth2#30]
Is it possible to add redirect_uri.

See https://dev.netatmo.com/apidocumentation/oauth

---
John

**Comment by CaseyRo** [comment]
@Dunnenj you could use the netatmo flow instead if you want to get data from netatmo and this one doesn't work 😉 https://flows.nodered.org/node/node-red-contrib-netatmo

**Comment by Dunnenj** [comment]
@CaseyRo that Node seems to stop working in October due to authentication changes made by Netatmo. Currently none of the contributors is responding.

**Comment by caputomarcos** [comment]
Hi @Dunnenj 
does this change help you?  OAuth2 Authorization Code grant support #27  let me know. 

Sincerely, Caputo.
