### ISSUE TITLE
oauth2 behind a proxy

### ISSUE THREAD

**Issue by cP0l0** [caputomarcos/node-red-contrib-oauth2#32]
Hello Guys,

First of all thanks a lot for this node. It is a awesome job !!!
My problem is I'm trying to use it behind a proxy. I have try many thing but nothing work.

There is a way to specify a proxy somewhere ?

Thanks a lot for your help.

.Christian

**Comment by b3belov** [comment]
I have the same problem.
I've discovered that axios module which is used from v4.0.2, has a bug related to proxy.
https://github.com/axios/axios/issues/3384

As a workaround I've downgraded to 4.0.1.

**Comment by caputomarcos** [comment]
![image](https://user-images.githubusercontent.com/3945941/229898212-dd302692-4ee5-421a-9441-24a2a8724f75.png)

The `oauth2.json` file has been updated to include new keys `use-proxy`, `proxy-config`, and `senderr`. 
In the `oauth2.html` file, a new form field is added for Proxy Configuration with two sub-fields - `Use proxy` and `Proxy Configuration`.

### In the oauth2.js file, the following changes were made:
* New constants axios and httpsProxyAgent are imported, which seems to be used to provide support for proxy configuration. Looks good.
* The oauth2Request function is updated to add support for proxy configuration, which looks fine.
* The handleResponse function is updated to send non-2xx responses to the Catch node when senderr option is enabled, which looks good.
* The oauth2 node is updated to handle the use-proxy and proxy options when they are enabled, which seems fine.

**Comment by caputomarcos** [comment]
hi folks,

Resolved bug and added support for proxy configuration. Proxy configuration options added to oauth2.json and oauth2.html files. Updated oauth2.js file to support proxy configuration using axios and httpsProxyAgent modules. Non-2xx responses are now sent to Catch node when senderr option is enabled. Proxy functionality will be available in release 5.0.0.

kind regards
