### ISSUE TITLE
node-red-contrib-oauth2 unable to send "audience" in msg body.

### ISSUE THREAD

**Issue by smoncada-paack** [caputomarcos/node-red-contrib-oauth2#33]
Hi all , 

We are building an OT-Iot ingestion service from a PLC/nodered installed on a Siemens IOT2050.

We are trying to send JSON REST to our API gateway behind CloudFlare and we use Auth0 to authenticate M2M communications.
In order to configure M2M we specify "client_Id" and "client_secret" and "audience" variables in the BODY of the TOKEN request.

Our Auth0 API PUSH works perfectly using a PostMan collection. 
But when we try your module we cannot specify the "audience" value in the BODY , only in the HEADER. Then Auth0 responds with a : 

oauth2Response: object
error: "access_denied"
error_description: "No audience parameter was provided, and no default audience has been configured"

There is an option to add "audience" parameter in the BODY of the request instead of the HEADER ?

Thank you in advance.-

**Comment by smoncada-paack** [comment]
I've created a new branch where I will hardcode the "audience"  parameter to test.

**Comment by caputomarcos** [comment]
> Hi all ,
> 
> We are building an OT-Iot ingestion service from a PLC/nodered installed on a Siemens IOT2050.
> 
> We are trying to send JSON REST to our API gateway behind CloudFlare and we use Auth0 to authenticate M2M communications. In order to configure M2M we specify "client_Id" and "client_secret" and "audience" variables in the BODY of the TOKEN request.
> 
> Our Auth0 API PUSH works perfectly using a PostMan collection. But when we try your module we cannot specify the "audience" value in the BODY , only in the HEADER. Then Auth0 responds with a :
> 
> oauth2Response: object error: "access_denied" error_description: "No audience parameter was provided, and no default audience has been configured"
> 
> There is an option to add "audience" parameter in the BODY of the request instead of the HEADER ?
> 
> Thank you in advance.-

Hello my dear friend,

I'm starting to analyze the mentioned bug and to carry out the tests it would be interesting to get your flow. Could you please provide it?

Best regards =)
