### ISSUE TITLE
Response type error

### ISSUE THREAD

**Issue by NZX-DeSiGN** [caputomarcos/node-red-contrib-oauth2#36]
Hi,

I'm trying to integrate the TickTick todo API, it's almost working, but after login into TickTick, I'm getting an error from the api : 
 ```Invalid response type```

It must be set to ```code``` ([TickTick API documentation](https://developer.ticktick.com/docs#/openapi))
How could I fix it please ?

Thank you !

**Comment by caputomarcos** [comment]
Hi @NZX-DeSiGN ,

Thank you for reaching out. Have you tried testing the integration with version 4.1.5 of the TickTick todo API? If not, please try using that version and let me know if the issue persists.

Also, could you please provide more information on how you are currently making the API request? It would be helpful to see the code snippet or the request details to identify the cause of the issue.

Looking forward to your response.

kind regards.

**Comment by caputomarcos** [comment]
![image](https://user-images.githubusercontent.com/3945941/230649179-b43b8cd6-5c78-40df-8464-0423c9e0067f.png)

![image](https://user-images.githubusercontent.com/3945941/230649293-72711b81-57fa-4b7f-8720-8655cc29f73f.png)
![image](https://user-images.githubusercontent.com/3945941/230649321-c27f5305-77b7-49b3-b2dd-cb8d6934f463.png)

![image](https://user-images.githubusercontent.com/3945941/230649504-9f8dfeb4-b427-425e-989a-dafaa65e9efa.png)

**Comment by NZX-DeSiGN** [comment]
Thank you, I'll check this week !
