### ISSUE TITLE
redirect_uri

### ISSUE THREAD

**Issue by gustavocaloi** [caputomarcos/node-red-contrib-oauth2#47]
Hi,
Will the "redirect_uri" parameter be implemented at some point for authentication calls?
I need to send the "redirect_uri" parameter to receive the token and I get the error: "Invalid redirect_uri that does not match with any redirect_uri created with the application"

**Comment by gustavocaloi** [comment]
Referencia de uma chamada de autenticação em DJANGO: https://github.com/gustavocaloi/ContaAzul-API

**Comment by caputomarcos** [comment]
@gustavocaloi 

v4.1.4 
https://flows.nodered.org/node/node-red-contrib-oauth2

# URI de redirecionamento
![image](https://user-images.githubusercontent.com/3945941/227729721-785d0dea-e9ea-4baa-9298-40b4d865be82.png)

# Edit oauth2 node
![image](https://user-images.githubusercontent.com/3945941/227729676-6a7c524f-2b53-4b18-92ca-82148c8161b2.png)

# Test 01
![image](https://user-images.githubusercontent.com/3945941/227729802-4a69c15a-0829-4f1c-8896-b9d4c92c0a3d.png)

## redirect 
![image](https://user-images.githubusercontent.com/3945941/227729829-3cf75056-92b4-4946-905c-114130039143.png)

## payload 
![image](https://user-images.githubusercontent.com/3945941/227729892-4b0877cf-5acd-452f-bcd4-ee5eab6894ea.png)

**Comment by gustavocaloi** [comment]
No fluxo do NodeRed eu acho "oauth2 node" e aciono o botão "Code" para obter o direcionamento e capturar o code?
<img width="1460" alt="Captura de Tela 2023-03-25 às 17 47 40" src="https://user-images.githubusercontent.com/19421257/227740940-23d397a0-7a9b-49d9-9a67-d5a57b91cbf3.png">
