### ISSUE TITLE
Support OAuth2 in an Microsoft Azure Service to Service Environment 

### ISSUE THREAD

**Issue by tglynx** [caputomarcos/node-red-contrib-oauth2#72]
Hi,

first of all, cool node. I was hoping that i can use this to authenticate against Dynamics 365 to pull some API data.
Unfortunately i failed using this node to authenticate as it has no option to send the 'resource' parameter necessary to authenticate.

I have the authentication working using a simple 'http request' node now. However, i would rather use a specialized node like this for this scenario.

Please have a look at this [Microsoft Documentation regarding Service to Service Calls Using Client Credentials](https://learn.microsoft.com/en-us/previous-versions/azure/dn645543(v=azure.100)?redirectedfrom=MSDN)

As you can see, a parameter called 'resource' needs to be passed to get the access token from the 'Access Token URL'.

When i try to use your node i get the following error message: 
AADSTS900144: The request body must contain the following parameter: 'resource'.

The configuration i use: 
GrantType: Password 
Access Token URL: https://login.microsoftonline.com/xxxx-tenantid-xxxx/oauth2/token
Username: MySecretUser
Password: MySecretPassword
ClientID: the app-id of the azure registered app
Client-secret: AzureProvidedClientsecret

</> Scope: Not neccessary in this scenario!
I would need a 'resource' parameter instead having a value of something like: https://mydynamictenant.crm4.dynamics.com

Questions: 
Is there a way to pass a custom parameter that i missed? 
Would it be possible to implement support for this type of authentication (please note that i am using the 'Password' grant type - the Microsoft Document is about client credentials ... both should work... 

Thanks
Michael

**Comment by tglynx** [comment]
Some additional reading about the 'resource' parameter in OAuth2

https://learn.microsoft.com/en-us/previous-versions/azure/dn645545(v=azure.100)
https://datatracker.ietf.org/doc/html/rfc6749

Hope this helps...

**Comment by tglynx** [comment]
FYI ... I implemented the necessary changes to support the 'resource' parameter in my forked repo (main branch).
It works as expected for me ... 

before: 
![Bildschirm­foto 2023-07-04 um 18 38 50](https://github.com/caputomarcos/node-red-contrib-oauth2/assets/30650435/864d2352-be70-41e5-b85c-6559a5f9798e)
![Bildschirm­foto 2023-07-04 um 18 39 31](https://github.com/caputomarcos/node-red-contrib-oauth2/assets/30650435/ad6d47e9-860e-4066-8ad1-024603feac5b)

after:
![Bildschirm­foto 2023-07-04 um 18 39 58](https://github.com/caputomarcos/node-red-contrib-oauth2/assets/30650435/5f506a29-fb64-41e7-8257-0e0c2d8365c6)

new UI for 'resource':
![Bildschirm­foto 2023-07-04 um 18 40 37](https://github.com/caputomarcos/node-red-contrib-oauth2/assets/30650435/bc226576-45df-4ec6-a1a3-32675e904def)

Let me know if it is appropriate to create a pull request.

Best Regards,
Michael

**Comment by caputomarcos** [comment]
Hello Michael,

First off, a big thank you for your deep dive into the OAuth2 implementation in the Microsoft Azure Service to Service environment. It's clear you've been on quite the journey trying to extract API data from Dynamics 365, only to discover the 'resource' parameter was missing from our node. Quite the plot twist!

I see you've managed to find a workaround using a simple 'http request' node - a testament to your resourcefulness. However, I understand your preference for a specialized node, designed specifically for this kind of mission.

Your shared Microsoft Documentation and additional reading about the 'resource' parameter in OAuth2 have been incredibly enlightening. It's like you've given us a roadmap to better understand this issue.

And let's not forget your initiative in implementing the necessary changes in your forked repo to accommodate the 'resource' parameter. It's fantastic to see that these modifications have been successful. Your before-and-after screenshots clearly illustrate the transformation and the improved user interface for the 'resource' parameter.

As for your pull request - absolutely, go ahead! It's like you've discovered a new path and now you're inviting us to join you. We'll review your changes and, if everything looks good, we'll be more than happy to integrate your updates into the project.

Once again, Michael, thank you for your significant contribution. You've turned a challenge into an opportunity for improvement. If you need further assistance or have more insights to share, don't hesitate to reach out. We're all in this together!

Best regards,

Caputo.

**Comment by tglynx** [comment]
Hi Caputo, 
thank you so much for all the kind words! I will try my best to create a decent pull request (never done this before).
Happy to contribute!

Regards,
Michael
