### ISSUE TITLE
Include token/auth url in output

### ISSUE THREAD

**Issue by bakman2** [caputomarcos/node-red-contrib-oauth2#75]
Thanks for creating this node - I have yet to fully explore its capabilities but getting access/refresh token was super simple so off to a great start.

Would it be useful if the output includes the access token url and authorization endpoint url, so these things dont have to be repeated when (re)creating payloads for refreshing ?

**Comment by caputomarcos** [comment]
Hi @bakman2,

Thank you for your feedback! We're glad to hear that you're finding the node useful and easy to work with.

We have already included the access token URL and authorization endpoint URL in the output to simplify the process of creating payloads for refreshing tokens. This should save you from having to repeat these details when (re)creating payloads.

If you have any more suggestions or need further assistance, feel free to let us know.

Best regards.
