### ISSUE TITLE
Embedded credentials for grant type Client Credentials

### ISSUE THREAD

**Issue by AMWN** [caputomarcos/node-red-contrib-oauth2#76]
I have a situation where the client credentials (client ID and Client Secret) has to be in the body of the request. 
Right now this is only possible for grant type password. 

Would be nice if you could add that.

**Comment by caputomarcos** [comment]
The latest versions of `node-red-contrib-oauth2` already include this feature. Now, you can include the client credentials (client ID and client secret) in the body of the request for all grant types.

### How to Use

To include the client credentials in the body of the request for any grant type, follow these steps:

1. **Node Configuration:**
   - Open the OAuth2 node configuration in Node-RED.
   - Enable the option `client_credentials_in_body`.

This feature was introduced in recent updates, enhancing the flexibility of the OAuth2 node to meet various authentication requirements.

If you have any issues or need further assistance, feel free to reach out!
