### ISSUE TITLE
Check if acces token is stil valid

### ISSUE THREAD

**Issue by AMWN** [caputomarcos/node-red-contrib-oauth2#77]
An idea is to add an option to let this node store the acces_token (node context), and check if it's still valid within the next call. 
I my case the acces_token expires in 3600,  so no new acces_token is required.

**Comment by caputomarcos** [comment]
Thank you for your suggestion! We have implemented the feature to store the access_token and check its validity for the next call. This will ensure that a new access_token is not requested unnecessarily if the current one is still valid. This feature will be included in the next release. Stay tuned!

Best regards,
The Team
