### ISSUE TITLE
the layout of the properties in node-red broken 

### ISSUE THREAD

**Issue by BorisDaich** [caputomarcos/node-red-contrib-oauth2#8]
while in the 1.0.6 version the properties html layout is OK 
in the new 1.1.0  version the properties html  layout  is totally broken
![image](https://user-images.githubusercontent.com/406865/86251114-1f337a80-bbba-11ea-845a-9e23633434be.png)

**Comment by chiranjeevibmse** [comment]
#10 Fixed and tested with node red v1.1.3

**Comment by cmdares** [comment]
node-red 1.2.1 has been broken!
Hope it can be repaired in time.
Thanks.
@chiranjeevibmse

**Comment by chiranjeevibmse** [comment]
![image](https://user-images.githubusercontent.com/4295489/96367248-4bbfd200-116a-11eb-8bac-044e2b98a4ef.png)
@cmdares  its fine see here
![image](https://user-images.githubusercontent.com/4295489/96367269-73169f00-116a-11eb-9393-8859b2fb9460.png)

**Comment by franadoriv** [comment]
Broken again on Node 1.2.5
![image](https://user-images.githubusercontent.com/9558104/101369851-1c1c8300-38ec-11eb-81ea-13ab4b5bad22.png)

**Comment by chiranjeevibmse** [comment]
not able find the root cause why this not working in every build, any input to fix this?
